// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sea.Models;

#nullable disable

namespace Sea.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730112115_AddMoreMarineAnimals")]
    partial class AddMoreMarineAnimals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sea.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "جميع الأسماك البحرية الموجودة في المياه السعودية",
                            ImageUrl = "/images/fish-category.jpg",
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 2,
                            Description = "الكائنات البحرية الضارة أو السامة التي يجب الحذر منها",
                            ImageUrl = "/images/dangerous-category.jpg",
                            Name = "Dangerous"
                        });
                });

            modelBuilder.Entity("Sea.Models.FirstAid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FishId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FishId");

                    b.ToTable("FirstAids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Wash the wound with clean water, stop bleeding, and seek medical help immediately.",
                            FishId = 3,
                            ImageUrl = "/images/Barracuda.jpg",
                            Title = "Barracuda Bite"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Place the injured area in hot water for 30-90 minutes and go to the hospital.",
                            FishId = 4,
                            ImageUrl = "/images/Lionfish.jpg",
                            Title = "Lionfish Sting"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Call emergency services immediately and soak the wound in hot water.",
                            FishId = 5,
                            ImageUrl = "/images/Stonefish.jpg",
                            Title = "Stonefish Sting"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Call emergency services immediately. Do not wait for symptoms.",
                            FishId = 7,
                            ImageUrl = "/images/Pufferfish.jpg",
                            Title = "Pufferfish Poisoning"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Rinse with seawater and use vinegar if available. Do not rub the skin.",
                            FishId = 14,
                            ImageUrl = "/images/Jellyfish.jpg",
                            Title = "Jellyfish Sting"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Wash the wound with clean water, control bleeding, cover it with a sterile dressing, and seek medical attention to prevent infection.",
                            FishId = 20,
                            ImageUrl = "/images/MorayEel.jpg",
                            Title = "Moray Eel Bite"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Keep the victim calm and still, immobilize the affected limb, and seek emergency medical care immediately. Do not cut the wound or try to suck out the venom.",
                            FishId = 21,
                            ImageUrl = "/images/SeaSnake.jpg",
                            Title = "Sea Snake Bite"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Control bleeding, soak the injured area in hot (not boiling) water for 30–90 minutes, clean the wound, and seek medical attention immediately.",
                            FishId = 22,
                            ImageUrl = "/images/Stingray.jpg",
                            Title = "Stingray Injury"
                        });
                });

            modelBuilder.Entity("Sea.Models.Fish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BreedingSeason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDangerous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdible")
                        .HasColumnType("bit");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxAge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prevention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Fish");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BreedingSeason = "Summer",
                            CategoryId = 1,
                            Description = "من أشهر أسماك البحر الأحمر ويؤكل بكثرة.",
                            ImageUrl = "/images/Grouper.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Red Sea & Arabian Gulf",
                            MaxAge = "20 years",
                            MaxSize = "1 meter",
                            Name = "Red Sea Grouper (الهامور)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 2,
                            BreedingSeason = "Spring",
                            CategoryId = 1,
                            Description = "سمكة سريعة ومهمة اقتصاديًا في السعودية.",
                            ImageUrl = "/images/Kingfish.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Red Sea & Arabian Gulf",
                            MaxAge = "20 years",
                            MaxSize = "2 meters",
                            Name = "Kingfish (الكنعد)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 3,
                            BreedingSeason = "Summer",
                            CategoryId = 2,
                            Description = "مفترس بحري سريع وقد يكون خطير.",
                            ImageUrl = "/images/Barracuda.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea",
                            MaxAge = "14 years",
                            MaxSize = "1.5 meters",
                            Name = "Barracuda (الباراكودا)",
                            Prevention = "Avoid swimming near it"
                        },
                        new
                        {
                            Id = 4,
                            BreedingSeason = "All year",
                            CategoryId = 2,
                            Description = "سمكة سامة ذات أشواك خطيرة.",
                            ImageUrl = "/images/Lionfish.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea",
                            MaxAge = "10 years",
                            MaxSize = "40 cm",
                            Name = "Lionfish (سمكة الأسد)",
                            Prevention = "Do not touch"
                        },
                        new
                        {
                            Id = 5,
                            BreedingSeason = "Spring",
                            CategoryId = 2,
                            Description = "أخطر سمكة سامة في العالم.",
                            ImageUrl = "/images/Stonefish.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea",
                            MaxAge = "10 years",
                            MaxSize = "50 cm",
                            Name = "Stonefish (سمكة الحجر)",
                            Prevention = "Avoid stepping on rocks"
                        },
                        new
                        {
                            Id = 6,
                            BreedingSeason = "Winter",
                            CategoryId = 1,
                            Description = "من أشهر أسماك الخليج العربي.",
                            ImageUrl = "/images/Hamour.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Arabian Gulf",
                            MaxAge = "15 years",
                            MaxSize = "1.2 meters",
                            Name = "Hamour (هامور الخليج)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 7,
                            BreedingSeason = "Summer",
                            CategoryId = 2,
                            Description = "سمكة سامة جدًا تحتوي على سم قاتل.",
                            ImageUrl = "/images/Pufferfish.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea & Arabian Gulf",
                            MaxAge = "10 years",
                            MaxSize = "60 cm",
                            Name = "Pufferfish (سمكة النفاخ)",
                            Prevention = "Do not eat or touch"
                        },
                        new
                        {
                            Id = 8,
                            BreedingSeason = "Spring",
                            CategoryId = 1,
                            Description = "سمكة سريعة تعيش في أسراب.",
                            ImageUrl = "/images/mackerel.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Arabian Gulf",
                            MaxAge = "10 years",
                            MaxSize = "50 cm",
                            Name = "Mackerel (الماكريل)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 9,
                            BreedingSeason = "Summer",
                            CategoryId = 2,
                            Description = "من أشهر المفترسات البحرية في العالم.",
                            ImageUrl = "/images/Shark.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea",
                            MaxAge = "30 years",
                            MaxSize = "6 meters",
                            Name = "Shark (القرش)",
                            Prevention = "Avoid deep water swimming"
                        },
                        new
                        {
                            Id = 10,
                            BreedingSeason = "Spring",
                            CategoryId = 1,
                            Description = "سمكة صغيرة تعيش في مجموعات كبيرة.",
                            ImageUrl = "/images/Sardine.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Arabian Gulf",
                            MaxAge = "5 years",
                            MaxSize = "30 cm",
                            Name = "Sardine (السردين)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 11,
                            BreedingSeason = "Summer",
                            CategoryId = 1,
                            Description = "سمكة ملونة تعيش قرب الشعاب المرجانية.",
                            ImageUrl = "/images/Parrotfish.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Red Sea",
                            MaxAge = "7 years",
                            MaxSize = "1 meter",
                            Name = "Parrotfish (سمكة الببغاء)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 12,
                            BreedingSeason = "All year",
                            CategoryId = 1,
                            Description = "سمكة صغيرة تعيش بين شقائق النعمان البحرية.",
                            ImageUrl = "/images/Clownfish.jpg",
                            IsDangerous = false,
                            IsEdible = false,
                            Locations = "Red Sea",
                            MaxAge = "6 years",
                            MaxSize = "15 cm",
                            Name = "Clownfish (سمكة المهرج)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 13,
                            BreedingSeason = "Summer",
                            CategoryId = 1,
                            Description = "كائن بحري يعيش لفترات طويلة.",
                            ImageUrl = "/images/Turtle.jpg",
                            IsDangerous = false,
                            IsEdible = false,
                            Locations = "Red Sea & Arabian Gulf",
                            MaxAge = "80 years",
                            MaxSize = "1.5 meters",
                            Name = "Sea Turtle (السلحفاة البحرية)",
                            Prevention = "Protected species"
                        },
                        new
                        {
                            Id = 14,
                            BreedingSeason = "Summer",
                            CategoryId = 2,
                            Description = "كائن بحري لاسع قد يسبب ألم شديد.",
                            ImageUrl = "/images/Jellyfish.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea",
                            MaxAge = "1 year",
                            MaxSize = "40 cm",
                            Name = "Jellyfish (قنديل البحر)",
                            Prevention = "Avoid touching"
                        },
                        new
                        {
                            Id = 15,
                            BreedingSeason = "Spring",
                            CategoryId = 1,
                            Description = "رخوي بحري سريع الحركة ويستخدم الحبر للدفاع.",
                            ImageUrl = "/images/Cuttlefish.jpeg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Arabian Gulf",
                            MaxAge = "2 years",
                            MaxSize = "50 cm",
                            Name = "Cuttlefish (الحبار)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 16,
                            BreedingSeason = "Summer",
                            CategoryId = 1,
                            Description = "من القشريات البحرية المنتشرة بالخليج.",
                            ImageUrl = "/images/Crab.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Arabian Gulf",
                            MaxAge = "4 years",
                            MaxSize = "25 cm",
                            Name = "Blue Crab (السلطعون الأزرق)",
                            Prevention = "Watch for claws"
                        },
                        new
                        {
                            Id = 17,
                            BreedingSeason = "Spring",
                            CategoryId = 1,
                            Description = "Popular food fish in Saudi Arabia.",
                            ImageUrl = "/images/emperor.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Red Sea & Arabian Gulf",
                            MaxAge = "15 years",
                            MaxSize = "80 cm",
                            Name = "Emperor Fish (الشعري)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 18,
                            BreedingSeason = "Summer",
                            CategoryId = 1,
                            Description = "Common reef fish.",
                            ImageUrl = "/images/Rabbitfish.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Red Sea",
                            MaxAge = "8 years",
                            MaxSize = "40 cm",
                            Name = "Rabbitfish (الصافي)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 19,
                            BreedingSeason = "Summer",
                            CategoryId = 1,
                            Description = "Widely consumed fish.",
                            ImageUrl = "/images/Tilapia.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Saudi coastal waters",
                            MaxAge = "10 years",
                            MaxSize = "60 cm",
                            Name = "Tilapia (البلطي)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 20,
                            BreedingSeason = "All year",
                            CategoryId = 2,
                            Description = "Can bite when threatened.",
                            ImageUrl = "/images/MorayEel.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea",
                            MaxAge = "30 years",
                            MaxSize = "2 meters",
                            Name = "Moray Eel (ثعبان البحر)",
                            Prevention = "Keep your distance"
                        },
                        new
                        {
                            Id = 21,
                            BreedingSeason = "Summer",
                            CategoryId = 2,
                            Description = "Highly venomous marine snake.",
                            ImageUrl = "/images/SeaSnake.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea",
                            MaxAge = "10 years",
                            MaxSize = "1.5 meters",
                            Name = "Sea Snake (ثعبان البحر السام)",
                            Prevention = "Never touch it"
                        },
                        new
                        {
                            Id = 22,
                            BreedingSeason = "Spring",
                            CategoryId = 2,
                            Description = "A marine ray with a venomous tail spine that can cause serious injuries.",
                            ImageUrl = "/images/Stingray.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea & Arabian Gulf",
                            MaxAge = "20 years",
                            MaxSize = "2 meters",
                            Name = "Stingray (اللخمة)",
                            Prevention = "Shuffle your feet while walking in shallow water and avoid touching it."
                        });
                });

            modelBuilder.Entity("Sea.Models.FirstAid", b =>
                {
                    b.HasOne("Sea.Models.Fish", "Fish")
                        .WithMany("FirstAids")
                        .HasForeignKey("FishId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Fish");
                });

            modelBuilder.Entity("Sea.Models.Fish", b =>
                {
                    b.HasOne("Sea.Models.Category", "Category")
                        .WithMany("Fish")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sea.Models.Category", b =>
                {
                    b.Navigation("Fish");
                });

            modelBuilder.Entity("Sea.Models.Fish", b =>
                {
                    b.Navigation("FirstAids");
                });
#pragma warning restore 612, 618
        }
    }
}
