// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sea.Models;

#nullable disable

namespace Sea.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428194112_SeedDate")]
    partial class SeedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sea.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "جميع الأسماك البحرية الموجودة في المياه السعودية",
                            ImageUrl = "/images/fish-category.jpg",
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 2,
                            Description = "الكائنات البحرية الضارة أو السامة التي يجب الحذر منها",
                            ImageUrl = "/images/dangerous-category.jpg",
                            Name = "Dangerous"
                        });
                });

            modelBuilder.Entity("Sea.Models.FirstAid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FishId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FishId");

                    b.ToTable("FirstAids");
                });

            modelBuilder.Entity("Sea.Models.Fish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BreedingSeason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDangerous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdible")
                        .HasColumnType("bit");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxAge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prevention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Fish");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BreedingSeason = "Summer",
                            CategoryId = 1,
                            Description = "من أشهر أسماك البحر الأحمر ويؤكل بكثرة.",
                            ImageUrl = "/images/grouper.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Red Sea & Arabian Gulf",
                            MaxAge = "20 years",
                            MaxSize = "1 meter",
                            Name = "Red Sea Grouper (الهامور)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 2,
                            BreedingSeason = "Spring",
                            CategoryId = 1,
                            Description = "سمكة سريعة ومهمة اقتصاديًا في السعودية.",
                            ImageUrl = "/images/kingfish.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Red Sea & Arabian Gulf",
                            MaxAge = "20 years",
                            MaxSize = "2 meters",
                            Name = "Kingfish (الكنعد)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 3,
                            BreedingSeason = "Summer",
                            CategoryId = 2,
                            Description = "مفترس بحري سريع وقد يكون خطير.",
                            ImageUrl = "/images/barracuda.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea",
                            MaxAge = "14 years",
                            MaxSize = "1.5 meters",
                            Name = "Barracuda (الباراكودا)",
                            Prevention = "Avoid swimming near it"
                        },
                        new
                        {
                            Id = 4,
                            BreedingSeason = "All year",
                            CategoryId = 2,
                            Description = "سمكة سامة ذات أشواك خطيرة.",
                            ImageUrl = "/images/lionfish.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea",
                            MaxAge = "10 years",
                            MaxSize = "40 cm",
                            Name = "Lionfish (سمكة الأسد)",
                            Prevention = "Do not touch"
                        },
                        new
                        {
                            Id = 5,
                            BreedingSeason = "Spring",
                            CategoryId = 2,
                            Description = "أخطر سمكة سامة في العالم.",
                            ImageUrl = "/images/stonefish.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea",
                            MaxAge = "10 years",
                            MaxSize = "50 cm",
                            Name = "Stonefish (سمكة الحجر)",
                            Prevention = "Avoid stepping on rocks"
                        },
                        new
                        {
                            Id = 6,
                            BreedingSeason = "Summer",
                            CategoryId = 1,
                            Description = "سمكة تجارية مهمة جدًا.",
                            ImageUrl = "/images/tuna.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Red Sea",
                            MaxAge = "8 years",
                            MaxSize = "2 meters",
                            Name = "Yellowfin Tuna (التونة الصفراء)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 7,
                            BreedingSeason = "Winter",
                            CategoryId = 1,
                            Description = "من أشهر أسماك الخليج العربي.",
                            ImageUrl = "/images/hamour.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Arabian Gulf",
                            MaxAge = "15 years",
                            MaxSize = "1.2 meters",
                            Name = "Hamour (هامور الخليج)",
                            Prevention = "No risk"
                        },
                        new
                        {
                            Id = 8,
                            BreedingSeason = "Summer",
                            CategoryId = 2,
                            Description = "سمكة سامة جدًا تحتوي على سم قاتل.",
                            ImageUrl = "/images/pufferfish.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea & Arabian Gulf",
                            MaxAge = "10 years",
                            MaxSize = "60 cm",
                            Name = "Pufferfish (سمكة النفاخ)",
                            Prevention = "Do not eat or touch"
                        },
                        new
                        {
                            Id = 9,
                            BreedingSeason = "Spring",
                            CategoryId = 2,
                            Description = "كائن بحري يعيش في القاع وذيله قد يكون سام.",
                            ImageUrl = "/images/eagleray.jpg",
                            IsDangerous = true,
                            IsEdible = false,
                            Locations = "Red Sea",
                            MaxAge = "15 years",
                            MaxSize = "3 meters",
                            Name = "Eagle Ray (اللخمة)",
                            Prevention = "Avoid touching"
                        },
                        new
                        {
                            Id = 10,
                            BreedingSeason = "Spring",
                            CategoryId = 1,
                            Description = "سمكة سريعة تعيش في أسراب.",
                            ImageUrl = "/images/mackerel.jpg",
                            IsDangerous = false,
                            IsEdible = true,
                            Locations = "Arabian Gulf",
                            MaxAge = "10 years",
                            MaxSize = "50 cm",
                            Name = "Mackerel (الماكريل)",
                            Prevention = "No risk"
                        });
                });

            modelBuilder.Entity("Sea.Models.FirstAid", b =>
                {
                    b.HasOne("Sea.Models.Fish", "Fish")
                        .WithMany()
                        .HasForeignKey("FishId");

                    b.Navigation("Fish");
                });

            modelBuilder.Entity("Sea.Models.Fish", b =>
                {
                    b.HasOne("Sea.Models.Category", "Category")
                        .WithMany("Fish")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sea.Models.Category", b =>
                {
                    b.Navigation("Fish");
                });
#pragma warning restore 612, 618
        }
    }
}
